import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { StarsCanvas } from "@/components/StarsCanvas"; 


const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",
});

export const metadata: Metadata = {
  title: "Faiq's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfit.variable} antialiased relative `}
      >
        <StarsCanvas />
        {children}
      </body>
    </html>
  );
}
